# -*- coding: utf-8 -*-
"""price_pred_backtesting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D6YYO5hX02Gr-TXrpe-evnsVcKWjUjv4
"""

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

import pandas as pd
import numpy as np
import datetime as dt
import timeit
import os.path

from google.colab import drive
drive.mount('/content/drive')



"""This Block Should Be The Only Section for User Input:"""

# User Input Section:

# directory that stores dataframes:
# naming of dataframes: YYYYMMDD.csv.gz
# dataframe needs to at least have the following columns:
# 'datetime', 'pred_chg', 'bid', 'ask', 'mid' (Note: 'pred_chg' is just y_hat)
prediction_dir = '/content/drive/My Drive/DL_Project/LSTM_Predicted_IH/'

# Output directory:
output_dir = '/content/drive/My Drive/DL_Project/lstm_strategy/'
# Output file name head: 
model_name = 'lstm'
# output file format: lstm_backtest_YYYYMMDD.csv; 
# will also have one summary file: lstm_pnl_summary.csv

backtest_start_date = '20180101'
backtest_end_date = '20181231'

# Trading Stratgy Parameters:
input_upside_thresh = 0.05  # when y_hat larger than this number, will long
input_downside_thresh = -0.05  # when y_hat less than this number, will short
input_take_profit = 2.5*0.2  # take profit threshold
input_stop_loss = -1.5*0.2  # stop loss threshold
input_holding_period = 30*2  # max holding period (30 seconds)
input_max_pos = 3  # max positions held





Morning_Start = dt.timedelta(hours=9, minutes=30)
Morning_End = dt.timedelta(hours=11, minutes=30)
Afternoon_Start = dt.timedelta(hours=13)
Afternoon_End = dt.timedelta(hours=15)



def add_trade_strategy(df, upside_thresh = 0.05,
            downside_thresh = -0.05,
            take_profit = 2.5 * 0.2,
            stop_loss = -1.5 * 0.2,
            holding_period = 30*2, # 30s
            max_pos = 3):  
  
  pos = []
  enter_time = []
  enter_price = []
  pos_holding = 0
  cash = 0.0
  action = 0
  # enter_price = np.nan
  df['pos'] = 0.0
  df['cash'] = 0.0
  df['action'] = 0

  for i in df.index:
    
    # take profit / stop loss / off load existing position
    action = 0
    offload = []
    new_pos = []
    new_enter_time = []
    new_enter_price = []
    for p in range(len(pos)):
      if (((df.loc[i, 'mid'] - enter_price[p])*pos[p] < stop_loss) or
         ((df.loc[i, 'mid'] - enter_price[p])*pos[p] > take_profit) or
         ((i - enter_time[p]) >= holding_period)):
        off_load.append(p)
        if pos[p] > 0:  # offload long position
          action -= 1
          cash += df.loc[i, 'bid']
        else:  # offload short position
          action += 1
          cash -= df.loc[i, 'ask']
      else:
        new_pos.append(pos[p])
        new_enter_time.append(enter_time[p])
        new_enter_price.append(enter_price[p])
    
    pos = new_pos       
    enter_time = new_enter_time  
    enter_price = new_enter_price
    pos_holding = len(pos)


    # Enter into new positions based on prediction:
    if pos_holding < max_pos:
      if df.loc[i, 'pred_chg'] < downside_thresh:    
        pos.append(-1)
        enter_price.append(df.loc[i, 'mid'])
        enter_time.append(i)
        cash += df.loc[i, 'bid']
        action -= 1
      elif df.loc[i, 'pred_chg'] > upside_thresh:    
        pos.append(1)
        enter_price.append(df.loc[i, 'mid'])
        enter_time.append(i)
        cash -= df.loc[i, 'ask']
        action += 1


    df.loc[i, 'pos'] = sum(pos)
    df.loc[i, 'cash'] = cash
    df.loc[i, 'action'] = action
  
  df['cum_pnl'] = df['pos'] * df['mid'] + df['cash']
  return df



def build_one_day_IH(df, morning_session_start, morning_session_end,
           afternoon_session_start, afternoon_session_end,
           pnl_dict,
           upside_thresh,
           downside_thresh,
           take_profit,
           stop_loss,
           holding_period,
           max_pos):
  
  df = df[['datetime', 'pred_chg', 'bid', 'ask', 'mid']]

  df['datetime'] = pd.to_datetime(df['datetime'])

  df_am = df[(df['datetime'] >= morning_session_start) & 
         (df['datetime'] <= morning_session_end)]
  df_pm = df[(df['datetime'] >= afternoon_session_start) & 
         (df['datetime'] <= afternoon_session_end)]

  df_am = add_trade_strategy(df_am, upside_thresh, downside_thresh, take_profit, stop_loss, holding_period, max_pos)
  df_pm = add_trade_strategy(df_pm, upside_thresh, downside_thresh, take_profit, stop_loss, holding_period, max_pos)
  
  pnl_dict['am'] = df_am['cum_pnl'].iloc[-1]
  pnl_dict['pm'] = df_pm['cum_pnl'].iloc[-1]

  # merge rows
  df = pd.concat([df_am, df_pm])
  return df





start_time = timeit.default_timer()

pnl_summary = {'date': [], 'am': [], 'pm': []}

for trade_date in pd.date_range(backtest_start_date, backtest_end_date):

  df_file_path = prediction_dir + trade_date.strftime('%Y%m%d') + '.csv.gz'  
  if not os.path.exists(df_file_path):
    continue
  
  print('Backtesting', trade_date.date())
  
  IH = pd.read_csv(df_file_path)
  
  morning_start = trade_date + Morning_Start
  morning_end = trade_date + Morning_End
  afternoon_start = trade_date + Afternoon_Start
  afternoon_end = trade_date + Afternoon_End
  
  pnl_cur = {'am': 0.0, 'pm': 0.0}

  IH = build_one_day_IH(IH, morning_start, morning_end,
              afternoon_start, afternoon_end, pnl_cur,
              input_upside_thresh,
              input_downside_thresh,
              input_take_profit,
              input_stop_loss, 
              input_holding_period,
              input_max_pos)
  
  pnl_summary['date'].append(trade_date.date())
  pnl_summary['am'].append(pnl_cur['am'])
  pnl_summary['pm'].append(pnl_cur['pm'])

  # IH_dropna = IH.dropna()
  IH.to_csv(output_dir + model_name + '_backtest_' + trade_date.strftime('%Y%m%d') + '.csv')

pnl_summary = pd.DataFrame.from_dict(pnl_summary)
pnl_summary['cum_pnl'] = pnl_summary['am'] + pnl_summary['pm']
pnl_summary.to_csv(output_dir + model_name + '_pnl_summary.csv')

print('Time took: ', timeit.default_timer() - start_time)





