# -*- coding: utf-8 -*-
"""two-way-table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bveukm16fumh2sJ9ThQvmRs4SQmEb_VM
"""

""" mount drive """

import os

GOOGLE_DIR = '/content/drive/My Drive/DL_Project'
LOCAL_DIR = '/home/ziyan/Desktop/Deep Learning Project'

def colab_mount_google_drive():
    drive.mount('/content/drive', force_remount=True)
    os.chdir(GOOGLE_DIR)
    os.listdir()

def mount_local_drive():
    os.chdir(LOCAL_DIR)
    os.listdir()

try:
    from google.colab import drive
    colab_mount_google_drive()
    DIR = GOOGLE_DIR
    print('Mounted google drive')
except ModuleNotFoundError:
    mount_local_drive
    DIR = LOCAL_DIR
    print('Mounted local drive')

res_dir = os.path.join(DIR, 'model_outputs/LSTM_256_1_128')
os.chdir(res_dir)
os.listdir()

result_file = 'mid_01s_2019-11-23T00:11:20.182736_output.csv'
path = os.path.join(res_dir, result_file)

import pandas as pd
df=pd.read_csv(result_file, names=['target', 'pred'])
df.head()

df.shape

def group_values(x):
    if x >= 0.04:
        return '>0.04'
    if 0.02 > x >= 0:
        return '0~0.02'
    elif 0.04 > x >= 0.02:
        return '0.02~0.04'
    elif x >= -0.02:
        return '-0.02~0'
    elif x >= -0.04:
        return '-0.04~-0.02'
    else:
        return '<-0.04'

df['target']=df['target'].apply(group_values)
df['pred']=df['pred'].apply(group_values)
print(df.head())

pd.crosstab([df['pred']], [df['target']])